parameters:
- name: subTaskKey
  type: string
  default: ''

steps:
- script: |
    echo $pwd
    # tar -czvf $(TARGET)-$(ResourceProvider)-generated.tar.gz generated/$(ResourceProvider)
    tar -czvf $(TARGET)-$(ResourceProvider)-generated.tar.gz $(Artifact)
    az login --service-principal -u $(SERVICE_PRINCIPE_ID) -p $(SERVICE_PRINCIPE_SECRET) --tenant $(SERVICE_PRINCIPE_TENANT)
    az storage blob upload -c depthcoverage -f $(TARGET)-$(ResourceProvider)-generated.tar.gz -n $(TARGET)/$(TARGET)-$(ResourceProvider)-generated.tar.gz --subscription $(SERVICE_PRINCIPE_SUBSCRIPTION) --account-name=depthcoverage
  condition: always()
  displayName: 'After $(TASK_KEY)'
- bash: |
    tar -czvf $(TARGET)-$(ResourceProvider)-log.tar.gz *.log
    az storage blob upload -c depthcoverage -f $(TARGET)-$(ResourceProvider)-log.tar.gz -n log/$(TARGET)/$(TARGET)-$(ResourceProvider)-log.tar.gz --subscription $(SERVICE_PRINCIPE_SUBSCRIPTION) --account-name=depthcoverage
  displayName: 'upload log'
- bash: |
    echo $(Pipeline.Workspace)
    pwd

    # sdktarget=$(TARGET)
    # if [ "$sdktarget" == "terraform" ]; then
    #   git clone --branch pipeline https://github.com/$(TF_ORG)/terraform-provider-azurerm.git
    #   cd ./terraform-provider-azurerm
    # fi

    # if [ "$sdktarget" == "clicore" ] || [ "$sdktarget" == "cliextension" ]; then
    #   git clone https://github.com/$(CLI_ORG)/azure-cli
    #   cd ./azure-cli
    # fi

    # git config credential.helper store; git config --global user.email "chunyu@microsoft.com";git config --global user.name "chunyu3;"
    # git checkout -b $(TARGET)$(ResourceProvider); git branch; git add -A; git commit -m "autogenerated"; git push origin $(TARGET)$(ResourceProvider);
  displayName: 'submit to focked code repo'