steps:
- bash: |
    ls -l
    pwd
    echo "https://$(PIPELINE_USER):${PIPELINE_TOKEN}@github.com" > ~/.git-credentials
    git clone --branch pipeline https://${PIPELINE_USER}:${PIPELINE_TOKEN}@github.com/${TF_ORG}/terraform-provider-azurerm.git
    git clone --branch depth-$(TARGET)-$(ResourceProvider) https://github.com/${Swagger_ORG}/azure-rest-api-specs.git
  displayName: 'Setup TF Test env'